default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :build do
    setup_ci if is_ci

    # Ensure certificate is installed
    cert(
      development: false,
      force: true,
      skip_set_partition_list: true
    ) if is_ci

    # Get provisioning profile
    sigh(
      app_identifier: "com.suqafuran.app",
      provisioning_name: "Suqafuran App Store",
      development: false,
      force: true,
      readonly: false,
      skip_certificate_verification: true
    ) if is_ci

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      configuration: "Release",
      clean: true,
      output_directory: "~/Desktop/SuqafuranIPA",
      output_name: "Suqafuran.ipa",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        stripSwiftSymbols: true,
        uploadBitcode: true,
        teamID: "2969422VU2",
        provisioningProfileName: "Suqafuran App Store"
      }
    )

    upload_to_testflight(
      ipa: "~/Desktop/SuqafuranIPA/Suqafuran.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
