default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :build do
    setup_ci if is_ci

    # Certificate and provisioning profile are installed via workflow
    # xcodebuild will use them with -allowProvisioningUpdates

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      configuration: "Release",
      clean: true,
      sdk: "iphoneos",
      output_directory: "~/Desktop/SuqafuranIPA",
      output_name: "Suqafuran.ipa",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        stripSwiftSymbols: true,
        uploadBitcode: true,
        teamID: "2969422VU2"
      }
    )

    upload_to_testflight(
      ipa: "~/Desktop/SuqafuranIPA/Suqafuran.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
