"""default template

Revision ID: 2afc0c522f7b
Revises: prod_indexes_001
Create Date: 2026-02-23 15:05:33.451961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2afc0c522f7b'
down_revision = 'prod_indexes_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['adminarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminarea_level'), 'adminarea', ['level'], unique=False)
    op.create_index(op.f('ix_adminarea_name'), 'adminarea', ['name'], unique=False)
    op.create_table('emergencycontact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_area_id'], ['adminarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencycontact_service_type'), 'emergencycontact', ['service_type'], unique=False)
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('admin_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_area_id'], ['adminarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_name'), 'place', ['name'], unique=False)
    op.create_table('landmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmark_category'), 'landmark', ['category'], unique=False)
    op.create_index(op.f('ix_landmark_name'), 'landmark', ['name'], unique=False)
    op.create_table('kaalayheedhepin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('privacy_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kaalayheedhepin_code'), 'kaalayheedhepin', ['code'], unique=True)
    op.drop_index(op.f('ix_auditlog_timestamp'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_favorite_user_id'), table_name='favorite')
    op.alter_column('listing', 'views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('listing', 'leads',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_listing_boost_expires_at'), table_name='listing')
    op.drop_index(op.f('ix_listing_boost_level'), table_name='listing')
    op.drop_index(op.f('ix_listing_category_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_created_at'), table_name='listing')
    op.drop_index(op.f('ix_listing_feed'), table_name='listing')
    op.drop_index(op.f('ix_listing_fts'), table_name='listing', postgresql_using='gin')
    op.drop_index(op.f('ix_listing_owner_id'), table_name='listing')
    op.drop_index(op.f('ix_listing_status'), table_name='listing')
    op.drop_column('listing', 'search_vector')
    op.alter_column('mobiletransaction', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('mobiletransaction', 'is_rejected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_mobiletransaction_is_linked'), table_name='mobiletransaction')
    op.drop_index(op.f('ix_notification_user_read'), table_name='notification')
    op.drop_index(op.f('ix_promotion_listing_id'), table_name='promotion')
    op.drop_index(op.f('ix_promotion_status'), table_name='promotion')
    op.alter_column('subcategory', 'attributes_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('subcategory_category_id_fkey'), 'subcategory', type_='foreignkey')
    op.create_foreign_key(None, 'subcategory', 'category', ['category_id'], ['id'])
    op.drop_index(op.f('ix_transaction_wallet_id'), table_name='transaction')
    op.alter_column('user', 'profile_views',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=False)
    op.alter_column('user', 'profile_views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_transaction_wallet_id'), 'transaction', ['wallet_id'], unique=False)
    op.drop_constraint(None, 'subcategory', type_='foreignkey')
    op.create_foreign_key(op.f('subcategory_category_id_fkey'), 'subcategory', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subcategory', 'attributes_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_promotion_status'), 'promotion', ['status'], unique=False)
    op.create_index(op.f('ix_promotion_listing_id'), 'promotion', ['listing_id'], unique=False)
    op.create_index(op.f('ix_notification_user_read'), 'notification', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_mobiletransaction_is_linked'), 'mobiletransaction', ['is_linked'], unique=False)
    op.alter_column('mobiletransaction', 'is_rejected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('mobiletransaction', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.add_column('listing', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || (COALESCE(description, ''::character varying))::text))", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_listing_status'), 'listing', ['status'], unique=False)
    op.create_index(op.f('ix_listing_owner_id'), 'listing', ['owner_id'], unique=False)
    op.create_index(op.f('ix_listing_fts'), 'listing', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_listing_feed'), 'listing', ['status', 'boost_level', 'created_at'], unique=False)
    op.create_index(op.f('ix_listing_created_at'), 'listing', ['created_at'], unique=False)
    op.create_index(op.f('ix_listing_category_id'), 'listing', ['category_id'], unique=False)
    op.create_index(op.f('ix_listing_boost_level'), 'listing', ['boost_level'], unique=False)
    op.create_index(op.f('ix_listing_boost_expires_at'), 'listing', ['boost_expires_at'], unique=False)
    op.alter_column('listing', 'leads',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('listing', 'views',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_favorite_user_id'), 'favorite', ['user_id'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.create_index(op.f('ix_auditlog_timestamp'), 'auditlog', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_kaalayheedhepin_code'), table_name='kaalayheedhepin')
    op.drop_table('kaalayheedhepin')
    op.drop_index(op.f('ix_landmark_name'), table_name='landmark')
    op.drop_index(op.f('ix_landmark_category'), table_name='landmark')
    op.drop_table('landmark')
    op.drop_index(op.f('ix_place_name'), table_name='place')
    op.drop_table('place')
    op.drop_index(op.f('ix_emergencycontact_service_type'), table_name='emergencycontact')
    op.drop_table('emergencycontact')
    op.drop_index(op.f('ix_adminarea_name'), table_name='adminarea')
    op.drop_index(op.f('ix_adminarea_level'), table_name='adminarea')
    op.drop_table('adminarea')
    # ### end Alembic commands ###
