default_platform(:ios)

platform :ios do
  desc "Build IPA"

  lane :build do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY'],
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    if is_ci
      sh("rm -rf ~/Library/Developer/Xcode/DerivedData/* || true")

      keychain_name = "fastlane_tmp_keychain"
      keychain_password = "fastlane123"

      create_keychain(
        name: keychain_name,
        password: keychain_password,
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )

      import_certificate(
        certificate_path: File.expand_path("../P72X8KV2P9.p12", __dir__),
        certificate_password: "",
        keychain_name: keychain_name,
        keychain_password: keychain_password
      )
    end

    sigh(
      api_key: api_key,
      app_identifier: "com.suqafuran.app",
      team_id: "2969422VU2",
      force: true
    )

    profile_name = lane_context[SharedValues::SIGH_NAME]

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      configuration: "Release",
      clean: true,
      sdk: "iphoneos",
      export_method: "app-store",
      output_directory: File.expand_path("~/Desktop/SuqafuranIPA"),
      output_name: "Suqafuran.ipa",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=2969422VU2 CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='#{profile_name}'",
      export_options: {
        method: "app-store",
        teamID: "2969422VU2",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.suqafuran.app" => profile_name
        }
      }
    )
  end
end
